blank_issues_enabled: true
contact_links:
  - name: Developer Community India Telegram
    url: https://t.me/joinchat/HEIlgBdl2oHdIRkYhkcPzw
    about: Ask any genral questions or queries here.
  - name: Developer Community India Forum
    url: https://devcom.cf/
    about: Make any discussions here.
